alias ls='ls -lah --color=auto --time-style=long-iso'
alias mount='sudo mount'
alias umount='sudo umount'
alias gd='rclone mount Google\ Drive: "$HOME"/Google\ Drive'
alias iso8601='date +%Y-%m-%dT%H\:%m\:%S'
