alias ls='ls --color'
alias l='ls -lAhv --time-style=long-iso'
alias ll='ls -lhv --time-style=long-iso'
alias la='ls -Ahv --time-style=long-iso'
alias 8601='date +%Y%m%dT%H%M%S'
alias 8601e='date +%Y-%m-%dT%H\:%M\:%S'
alias 8601u='echo $(8601 -u)Z'
alias 8601ue='echo $(8601e -u)Z'
alias cp='cp --reflink=auto'
alias sudo='sudo ' #pass aliases to sudo https://askubuntu.com/a/22043/863714
alias iomon='iostat --human 1 /dev/sd? /dev/mmcblk?' #io monitoring command
alias please='sudo '
alias fucking='sudo '
alias ip='ip --color'
alias e='$EDITOR'
alias et='emacsclient -t'
alias ec='emacsclient'
alias ecc='emacsclient -c'
alias nixos-update='sudo git -C /nix/var/nix/nixos-config reset --hard $NIXOS_REF'
alias nixpkgs-update='sudo git -C /nix/var/nix/nixpkgs reset --hard $NIXPKGS_REF'
alias nix-stray-roots='nix-store --gc --print-roots | egrep -v "^(/nix/var|/run/\w+-system|\{memory|\{censored|/proc/maps/)"'
