alias ls='ls --color=auto --time-style=long-iso'
alias ll='ls -lh --color=auto --time-style=long-iso'
alias la='ls -lAh --color=auto --time-style=long-iso'
alias gd='rclone mount Google\ Drive: "$HOME"/Google\ Drive'
alias iso8601='date +%Y-%m-%dT%H\:%m\:%S'
